### ISSUE TITLE
Hello can you help me? pls I don't know how to do the reader work

### ISSUE THREAD

**Issue by leosoulmon** [SebastianPozoga/raspi-web-nfc-reader-meet.php#1]
I want to use the nfc reader in my web site but I don't know how to install *libNFC *nfc-tools to make reader works, pls help me I need to know this. Can you do an easy tutorial for this or something like that?

**Comment by SebastianPozoga** [comment]
Hi.

I understand that you are writing with regard to my presentation:
http://www.slideshare.net/sebastianpozoga/meetphpgpio

I was install nfc-lib a few month ago and I don't remember all commands. 
What is your linux distribution??

You find description on 
http://nfc-tools.org/index.php?title=Libnfc#Installation

1) firstly you should install dependencies:
libusb, pcsc-lite (with pcscd), libccid

2) Use the commands:
wget http://libnfc.googlecode.com/files/libnfc-x.x.x.tar.gz
tar -xvzf libnfc-x.x.x.tar.gz
cd libnfc-x.x.x
./configure --prefix=/usr --sysconfdir=/etc
make

If you use debian/ubuntu:

1) dependecies:
sudo apt-get install libusb-dev libpcsclite-dev
sudo apt-get install libusb-0.1-4 libpcsclite1 libccid pcscd

2) libnfc:
git clone https://code.google.com/p/libnfc/
cd libnfc
git checkout libnfc-1.7.1
git clean -d -f -x
#rm ../libnfc*.deb
git remote|grep -q anonscm||git remote add anonscm 
git://anonscm.debian.org/collab-maint/libnfc.git
git fetch anonscm
git checkout remotes/anonscm/master debian
git reset
dpkg-buildpackage -uc -us -b

I am hope my email is helpful. If you have more questions write.

Beast Regards
Sebastian Pożoga

**Comment by leosoulmon** [comment]
ok, thanks. I'm trying here.

**Comment by leosoulmon** [comment]
Unhappily I don't use ubuntu. I use windows 7 and I have no choice I have to use it.

**Comment by SebastianPozoga** [comment]
The example was created for raspberrypi with raspbian. But you can try 
use ubuntu on virtual machine. Try VirtualBox and delegate host usb 
port. But I've never used this method.

**Comment by leosoulmon** [comment]
ok I'll try

**Comment by leosoulmon** [comment]
Thanks, Sebastian
I'll keep trying.
I need to do this work in windows platform.

**Comment by teddypeng** [comment]
SebastianPozoga, I install all of the module before run sudo php nfcService.php,but still not work on my pi, do you know whats that mean?
pi@teddypi:~/Documents/raspi-web-nfc-reader-meet.php-master $ sudo php nfcService.php
PHP Warning:  dl(): Dynamically loaded extensions aren't enabled in /home/pi/Documents/raspi-web-nfc-reader-meet.php-master/raspi/wiringpi.php on line 22

Warning: dl(): Dynamically loaded extensions aren't enabled in /home/pi/Documents/raspi-web-nfc-reader-meet.php-master/raspi/wiringpi.php on line 22
PHP Fatal error:  Call to undefined function pinMode() in /home/pi/Documents/raspi-web-nfc-reader-meet.php-master/raspi/wiringpi.php on line 47

Fatal error: Call to undefined function pinMode() in /home/pi/Documents/raspi-web-nfc-reader-meet.php-master/raspi/wiringpi.php on line 47

**Comment by SebastianPozoga** [comment]
Hi teddypeng,

Try this:
https://stackoverflow.com/questions/36668117/error-when-trying-to-dynamically-load-php-library

The source of your problem is wiringpi library. More details is here:
http://wiringpi.com

Enjoy it :-)

Best regards
Sebastian Pożoga

śr., 11.04.2018, 08:58 użytkownik teddypeng <notifications@github.com>
napisał:

**Comment by SebastianPozoga** [comment]
It is time to close the issue ;-)
